.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PACKAGE\.YML" "5" "December 2016" "" ""
.
.SH "NAME"
\fBpackage\.yml\fR \- Solus package build format
.
.SH "SYNOPSIS"
.
.nf

The Solus package build format, with YAML syntax\.
.
.fi
.
.SH "DESCRIPTION"
The primary format of package builds in Solus, \fBpackage\.yml(5)\fR provides a modern, declarative, and structured format in which to define metadata and steps, to convert a build operation into a package\.
.
.P
\fBypkg\-build(1)\fR will use the advanced patterns system and some very specific internal rules to automatically split the package into multiple packages, refered to here as "subpackages"\.
.
.SH "CONFIGURATION FORMAT"
\fBypkg\-build(1)\fR uses the YAML file format\. However, this is a very specialised flavour of YAML with very specific extensions and types\.
.
.P
\fBTypes\fR
.
.P
Some of the specialised types expected by \fBpackage\.yml(5)\fR are explained below\.
.
.IP "\(bu" 4
\fBdict(s)\fR
.
.IP
This is a set of one or more \fBkey\fR:\fBvalue\fR mappings\. These are always in a list format\.
.
.IP "\(bu" 4
\fBmultimap\fR
.
.IP
This is a \fBkey\fR:\fBvalue\fR mapping where the \fBkey\fR is IMPLICIT\. That is to say, it is acceptable to omit the key\. A single value passed as the \fBvalue\fR will set the implicit key\'s component\.
.
.IP
In all instances the implicit key is the \fBmain package\fR\. The \fBmultimap\fR format can accept a list instead of a string as a value, and each item in that list also follows the implicit key policy\.
.
.IP
For each item in the list, if the \fBkey\fR is EXPLICIT, by using \fBdict\fR style \fBkey\fR:\fBvalue\fR mapping, then the key specified will be used\.
.
.IP
Within \fBypkg(1)\fR, that key is always a package name\. This name should be the shortform name, not the fully qualified name, i\.e the subpackage name without the \fBname\fR prefix\.
.
.IP
This allows a general key to accept sane defaults, but also allows the key to be extended to override attributes of a subpackage\.
.
.IP "" 0
.
.P
\fBMandatory Keys\fR
.
.IP "\(bu" 4
\fBname\fR [string]
.
.IP
Set the name of the package\. In general this should try to match the upstream source name wherever possible\. All subpackages generated by \fBypkg\-build(1)\fR will have this \fBname\fR as a prefix\.
.
.IP "\(bu" 4
\fBversion\fR [string]
.
.IP
The version of the software being packaged\. This should match the upstream version, i\.e\. that of the tarball or git tag\.
.
.IP "\(bu" 4
\fBrelease\fR [integer]
.
.IP
Packages within Solus are updated by their \fBrelease number\fR\. This number must start at 1 in new packages, and be incremented for every new update or change to the package that is published\.
.
.IP
It is perfectly acceptable to push an update with a \fBlower version\fR by bumping the release number\.
.
.IP "\(bu" 4
\fBlicense\fR [string(s)]
.
.IP
One or more strings that identify the software license of this package\. This should in most cases be a recognised \fBSPDX\fR license name\.
.
.IP "" 4
.
.nf

  * https://spdx\.org/licenses/
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
\fBsource\fR [dict(s)]
.
.IP
This key expects a list of \fBkey\fR:\fBvalue\fR mappings, to declare the sources that this package will use\. A "simple source" could be a tarball, where the key is the upstream URL, and the value must be a valid \fBsha256sum(1)\fR for that tarball\.
.
.IP
You can list multiple sources and they will all be fetched for the build process, but only the first will be extracted\. You can locate these other sources during your build with the \fB$sources\fR variable\.
.
.IP
\fBgit(1)\fR sources are also supported, and can be identified by prefixing the URI with \fBgit|\fR\. The expected value should be a commit, sha reference, or a tag\.
.
.IP "\(bu" 4
\fBcomponent\fR [multimap]
.
.IP
This key sets the package component, that is to say, the logical unit of organisation that it belongs to\. Check \fBeopkg lc\fR for existing component names\.
.
.IP
\fBcomponent\fR is a multimap key, therefore if passed a single string value it will set the component for the main package\. However, you may instead pass a list of the subpackage names, and set their component individually using the map \fBvalue\fR\.
.
.IP "\(bu" 4
\fBsummary\fR [multimap]
.
.IP
Set the "short" description of a package, i\.e\. a one line explanation of what an item is\. Use the subpackage names in the explicit key for this multimap to override subpackage summaries\.
.
.IP "\(bu" 4
\fBdescription\fR [multimap]
.
.IP
Set the full description of a package, i\.e\. a more in depth explanation of the software/package\'s functionality\. This is the large description that will be displayed in \fBeopkg\fR and the \fBsolus\-sc\fR\. Use the subpackage names in the explicit key for this multimap to override subpackage descriptions\.
.
.IP "" 0
.
.SH "EXAMPLE"
.
.nf

# Complete package

name       : nano
version    : 2\.7\.1
release    : 63
source     :
    \- https://www\.nano\-editor\.org/dist/v2\.7/nano\-2\.7\.1\.tar\.xz : df5cbe69831d7394c0a32fb27373ab313335ea4dc586d6f4be4081eb1de857cd
license    :
    \- GPL\-3\.0
summary    : Small, friendly text editor inspired by Pico
component  : editor
description: |
    GNU nano is an easy\-to\-use text editor originally designed as a
    replacement for Pico, the ncurses\-based editor from the non\-free
    mailer package Pine (itself now available under the Apache License
    as Alpine)\.
setup      : |
    %configure \-\-enable\-utf8 \-\-docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install

# Git sources
source     :
    \- git|https://github\.com/solus\-project/ypkg\.git : v17\.0

# Multimap, deciphered
# Set the component for the main package to `system\.base`
component: system\.base

# Also setting the main component to `system\.base`
component:
    \- system\.base

# Set the component of the main package to system\.base, but set the
# component for subpackage `devel` to `programming\.devel`
component:
    \- system\.base
    \- devel: programming\.devel
.
.fi
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright © 2016 Ikey Doherty, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBsolbuild(1)\fR, \fBypkg(1)\fR \fBypkg\-build(1)\fR, \fBypkg\-install\-deps(1)\fR
.
.IP "\(bu" 4
https://wiki\.solus\-project\.com/Package\.yml
.
.IP "\(bu" 4
https://github\.com/solus\-project/ypkg
.
.IP "\(bu" 4
https://wiki\.solus\-project\.com/Packaging
.
.IP "\(bu" 4
https://spdx\.org/licenses/
.
.IP "" 0
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

