#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  This file is part of ypkg2
#
#  Copyright 2015-2016 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#

from ypkg2 import console_ui
import subprocess
import sys
import os


def main():
    if len(sys.argv) < 2:
        console_ui.emit_error("ypkg", "Please provide path to package.yml")
        sys.exit(1)

    needFakeroot = True
    if os.geteuid() == 0:
        if "FAKED_MODE" not in os.environ:
            needFakeroot = False

    args = " ".join(sys.argv[1:])
    try:
        subprocess.check_call("ypkg-install-deps {}".format(args), shell=True)
        if needFakeroot:
            sub = "fakeroot "
        else:
            sub = ""
        subprocess.check_call("{}ypkg-build {}".format(sub, args), shell=True)
    except Exception as e:
        print(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
